### ISSUE TITLE
Gowmy Toyly

### ISSUE THREAD

**Issue by Atamyrat2005** [Toylycker/Travel-Agency#1]
Saýt gowy bolupdyr dizaýn gowlamaly bolsa aýdaý bet pikirlem bar men emailima yazay @komputeratamyrat@gmail.com

**Comment by Toylycker** [comment]
Shukur gowy gowmy senem? Shuny goshup skypedan Yazay kyn gormesen

**Comment by Atamyrat2005** [comment]
Atamyrat would like to chat with you on Skype. It's free!

https://join.skype.com/invite/LgyAGTDhpykv
